### ISSUE TITLE
Buttons updates and replacements

### ISSUE THREAD

**Issue by auino** [kriskbx/whatsapp-sharing#17]
If I replace a WA button with another one, the new button is now hidden.
How can I reload it?
Otherwise, how can I change button's data attributes?

**Comment by kriskbx** [comment]
We didn't change the HTML insert code since the first release. Make sure you downloaded the latest release and the _whatsapp-button.js_ is loaded properly. You can check that by opening your Browsers JavaScript console. Type `waShBtn`. The output should look something like this: `function waShBtn()`.

**Comment by kriskbx** [comment]
Thanks @Ipno84 . I didn't understand the question at first. This solves it.
